Path + Return code (#27)
* Change a message with the right path

Indeed, the script is position independant, thus `./db` is not always
the path to the db.

* Add return codes

It allows automatic tests and, if everything is find, to reproduce 22ad329

diff --git a/dump b/dump
--- a/dump
+++ b/dump
@@ -1,5 +1,6 @@
 #!/bin/bash
 cd "$(dirname "$0")"
+. common/libc.sh
 if [[ $# < 1 ]]; then
   echo >&2 "Usage: $0 id [name1 [name2 ...]]"
   exit 2
@@ -11,7 +12,9 @@ if [[ $# == 0 ]]; then
 else
   names="$@"
 fi
+ls -1 "db/${id}."* >/dev/null 2>&1 || die "Invalid ID '$id'"
 for name in $names; do
   offset=`cat db/${id}.symbols | grep "^$name " | cut -d' ' -f2`
+  [ -z "$offset" ] && die "Invalid symbol '$name'"
   echo "offset_${name} = 0x${offset}"
 done
